apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzeXN0ZW0ucmVnaXN0cnkuZW5lY2kubmV0Ijp7InVzZXJuYW1lIjoiZGF0YTM1NHRlc3QiLCJwYXNzd29yZCI6IjJqWWRrM0c5IiwiYXV0aCI6IlpHRjBZVE0xTkhSbGMzUTZNbXBaWkdzelJ6az0ifX19
kind: Secret
metadata:
  name: app-reg
  namespace: app
type: kubernetes.io/dockerconfigjson