# apiVersion defines the versioned schema of this Kubernetes manifest.
apiVersion: v1
# kind specifies the type of Kubernetes resource to be created.
kind: Secret
# metadata contains data that helps define the Secret, such as its name and namespace.
metadata:
  # name is the unique name of the Secret within the namespace.
  name: app-secret
  # namespace is the namespace of the Secret.
  namespace: app
  # type defines the type of the Secret. In this case, it is an Opaque Secret, which means it contains arbitrary data.
type: Opaque
# data contains the actual secret data, encoded in base64.
data:
  # db-user is the database user name.
  db-user: bXlkYXRhYmFzZQ== # When decoded from base64, it is 'mydatabase'.
  # db-password is the database password.
  db-password: bXlwYXNzd29yZA== # When decoded from base64, it is 'mypassword'.