# apiVersion defines the versioned schema of this Kubernetes manifest.
apiVersion: v1
# kind specifies the type of Kubernetes resource to be created.
kind: Secret
# metadata contains data that helps define the secret in a unique way,
# such as its name and namespace.
metadata:
  # name is the unique name of the secret within the namespace.
  name: db-secret
  # namespace is the namespace in which the secret will be created.
  namespace: db
# type defines the type of the secret. In this case, it is an Opaque secret,
# which means it contains arbitrary data.
type: Opaque
# data contains the actual secret data, encoded in base64.
data:
  # db-user is the base64-encoded username for the database.
  db-user: bXlkYXRhYmFzZQ== # mydatabase (base64 decoded)
  # db-password is the base64-encoded password for the database.
  db-password: bXlwYXNzd29yZA== # mypassword (base64 decoded)